name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@4
        with: 
          python-version: "3.10"
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install rsconnect-python
      - run: rsconnect deploy shiny --server ${{secrets.CONNECT_SERVER}} --api-key ${{ secrets.CONNECT_API_KEY }} --name "shiny from CI"
